version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk
    environment:
      - ELASTICSEARCH_HOSTS:elasticsearch:9200
    depends_on:
      - elasticsearch
    
  metricbeat:
    user: root
    environment: 
      - output.elasticsearch.hosts=['elasticsearch:9200']
    command: ["metricbeat", "-e"]
      
    volumes:
      - "./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    image: elastic/metricbeat:7.14.0 
    container_name: metricbeat
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

networks:
  elk:
    driver: bridge
